### ISSUE TITLE
A little compatibility issue with ReservedFlashlightSlot v1.6.2

### ISSUE THREAD

**Issue by Multiname** [ustaalon/LethalCompany.LaserControl#4]
A laser pointer will control turrets only if the left alt is held

**Comment by ustaalon** [comment]
Hey, I could not understand if its a suggestion or if its an issue..? can you share more information about it

**Comment by sword11247** [comment]
you can make reserved slot be a toggle instead of hold go to core config and check focused slots to true

**Comment by Multiname** [comment]
If I pick up a laser pointer while playing with ReservedFlashlightSlot it will be placed in the reserved slot. I can turn on the pointer but it will not control turrets.

![image](https://github.com/ustaalon/LethalCompany.LaserControl/assets/36795381/7841e7d6-4159-4ac7-b88c-99f97cb85cb8)

But I can hold the left alt, turn on the pointer and it will control turrets

![image](https://github.com/ustaalon/LethalCompany.LaserControl/assets/36795381/4a1f3ea1-bc06-42eb-b397-2e24d77ef21b)

So I can use both mods, but it looks like it shouldn't be the way it is. That's all, just wanted to notify you.

**Comment by Multiname** [comment]
By the way, because of this I even thought at first that your mod doesn't work. But then I eventually realized what I need to do.

**Comment by ustaalon** [comment]
Hey @Multiname thanks for the further information. I will look into it and I will work on a solution for that.

**Comment by ustaalon** [comment]
Found the bug and successfully reproduced it. Working on it.

**Comment by ustaalon** [comment]
Hey @Multiname and @sword11247. Issue fixed and it will be available in the next release - v0.1.4. Release schedule for Sunday, February 4th
